config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "welcome#index"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :recipes, only: [:index, :show, :new, :create]
  resources :recipes_advanced_search, only: [:index]



  get '/verify/phone', to: 'verification#show_verification_form', as: 'show_verification_form'
  post 'verify/send_code', to: 'verification#send_code', as: "send_code"

  post "verify/verify_code", to: "verification#verify_code", as: "verify_code"
  get "verify/show_confirmation_form", to: "verification#show_confirmation_form", as: "show_confirmation_form"
  

  resources :dashboard, only: [:index]
  resources :user_recipes, only: [:create]
  delete "/user_recipes", to: "user_recipes#destroy" # hand-rolled to avoid needing an ID

end

app/controllers/verification_controller.rb
class VerificationController < ApplicationController
  before_action :authenticate_user!

  def show_verification_form
  end

  def send_code
    if request.post?
      phone_number = params[:phone_number]
      service = TwilioVerifyService.new
      verification = service.send_verification_code(phone_number)

      if verification.status == "pending"
        redirect_to show_confirmation_form_path(phone_number: phone_number), notice: "Verification code sent successfully"
      else
        redirect_to show_verification_form_path, notice: "Unable to send verification code. Please Try Again"
      end
    else
      # Handles invalid GET method
      render plain: "Method Not Allowed", status: :method_not_allowed
    end
  end

  def show_confirmation_form
    @phone_number = params[:phone_number]
  end

  def verify_code
    if request.post?
      phone_number = params[:phone_number]
      service = TwilioVerifyService.new
      verification_check = service.check_verification_code(phone_number, params[:code])

      if verification_check.status == "approved"
        current_user.verify_two_factor_auth
        redirect_to root_path, notice: "Phone number verified successfully"
      else
        render :show_confirmation_code, notice: "Unable to verify code. Please Try Again"
      end
    else
      # Handles invalid GET method
      render plain: "Method Not Allowed", status: :method_not_allowed
    end
  end
end

app/views/verification/show_confirmation_form.html.erb
<%= form_with url: verify_code_path, method: :post, local: true do |f| %>
  <%= f.label :code, "Enter your verification code" %>
  <%= f.text_field :code %>
  <%= f.submit "Verify" %>
  <%= hidden_field_tag :phone_number, @phone_number %>
<% end %>

app/views/verification/show_verification_form.html.erb
<%= form_with url: send_code_path, method: :post, local: true do |f| %>
  <div class="send_code">
    <%= label_tag :phone_number, "Enter your phone number with country code" %>
    <%= text_field_tag :phone_number %>
    <%= f.submit "Send Verification Code" %>
  </div>
<% end %>