config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "welcome#index"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :recipes, only: [:index, :show, :new, :create]
  resources :recipes_advanced_search, only: [:index]



  get '/verify/phone', to: 'verification#show_verification_form', as: 'show_verification_form'
  post 'verify/send_code', to: 'verification#send_code', as: "send_code"

  post "verify/verify_code", to: "verification#verify_code", as: "verify_code"
  get "verify/show_confirmation_form", to: "verification#show_confirmation_form", as: "show_confirmation_form"
  

  resources :dashboard, only: [:index]
  resources :user_recipes, only: [:create]
  delete "/user_recipes", to: "user_recipes#destroy" # hand-rolled to avoid needing an ID

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipe_facade = RecipeFacade.new(params[:search])
  end

  def show
    recipe_id = params[:id]
    @recipe_facade = RecipeShowFacade.new(recipe_id)
  end

  def new
  end

  def create
    params_hash = {
      "title" => params[:title],
      "image" => params[:image],
      "servings" => params[:servings],
      "prep_time" => params[:prep_time],
      "ingredients" => params[:ingredients],
      "instructions" => params[:instructions]
    }
    s3 = Aws::S3::Resource.new(region:'us-east-1')
    bucket = s3.bucket('turingconsultancy')

    obj = bucket.object(params[:image].original_filename)
    obj.upload_file(params[:image].tempfile, acl:'private')

    params_hash["image"] = obj.public_url

    response = RecipeDatabaseService.new.create_recipe(params_hash)

    if response.status == 204
      flash[:success] = "Recipe Created Successfully"
      redirect_to "/dashboard"
    else
      flash[:error] = "Something went wrong. Please try again."
      redirect_to "/recipes/new"
    end
  end
end

app/views/recipes/index.html.erb
<!DOCTYPE html>

<html lang="en-us"><head>
  <meta charset="utf-8">
  <title>Kind Kitchen</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="This is meta description">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Hugo 0.74.3" />
  
  <!-- theme meta -->
  <meta name="theme-name" content="reader" />

  <!-- plugins -->
  <link rel="stylesheet" href="plugins/bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">
  <link rel="stylesheet" href="plugins/slick/slick.css">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="css/style.css" media="screen">

  <!--Favicon-->
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
  <link rel="icon" href="images/favicon.png" type="image/x-icon">

  <meta property="og:title" content="Reader | Hugo Personal Blog Template" />
  <meta property="og:description" content="This is meta description" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="" />
  <meta property="og:updated_time" content="2020-03-15T15:40:24+06:00" />
</head>
<body>
  <!-- navigation -->
<header class="navigation fixed-top">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-white">
      <a class="navbar-brand order-1" href="/recipes">
        <h2>KindKitchen</h2>
      </a>
      <div class="collapse navbar-collapse text-center order-lg-2 order-3" id="navigation">
        <ul class="navbar-nav mx-auto">

        <ul class="navbar-nav ms-auto">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "My Dashboard", dashboard_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%#= link_to "Register", register_path, class: 'nav-link' %>
              <%= link_to "Create Account", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%#= link_to "Log In", login_path, class: 'nav-link' %>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        </ul>
      </div>

      <div class="order-2 order-lg-3 d-flex align-items-center">
        
        <!-- search -->
        <%= form_with url: recipes_path, method: :get, local: true, data: {turbo: false}, class: "header-search-form" do |f| %>
          <%= f.text_field :search, placeholder: "Search by Ingredients..." %>
          <%= f.submit "Search" %>
        <% end %>
      </div>

    </nav>
  </div>
</header>
<!-- /navigation -->

<!-- start of banner -->
<div class="banner text-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 mx-auto">
        <h1 class="mb-5">What Would You <br> Like To Cook Today?</h1>
        <div class="d-flex justify-content-center">
          <%= form_with url: recipes_path, method: :get, local: true, data: {turbo: false}, class: "default-search-form" do |f| %>
            <%= f.text_field :search, placeholder: "Search by Ingredients..." %>
            <%= f.submit "Search" %> 
          <% end %>
            <%= button_to "Advanced Search", recipes_advanced_search_index_path, method: :get, data: { turbo: false } %>
          </div>
      </div>
    </div>
  </div>
  
  <svg class="banner-shape-1" width="39" height="40" viewBox="0 0 39 40" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z" stroke="#040306"
      stroke-miterlimit="10" />
    <path class="path" d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z" />
    <path d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z" stroke="#040306"
      stroke-miterlimit="10" />
  </svg>
  
  <svg class="banner-shape-2" width="39" height="39" viewBox="0 0 39 39" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g filter="url(#filter0_d)">
      <path class="path"
        d="M24.1587 21.5623C30.02 21.3764 34.6209 16.4742 34.435 10.6128C34.2491 4.75147 29.3468 0.1506 23.4855 0.336498C17.6241 0.522396 13.0233 5.42466 13.2092 11.286C13.3951 17.1474 18.2973 21.7482 24.1587 21.5623Z" />
      <path
        d="M5.64626 20.0297C11.1568 19.9267 15.7407 24.2062 16.0362 29.6855L24.631 29.4616L24.1476 10.8081L5.41797 11.296L5.64626 20.0297Z"
        stroke="#040306" stroke-miterlimit="10" />
    </g>
    <defs>
      <filter id="filter0_d" x="0.905273" y="0" width="37.8663" height="38.1979" filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB">
        <feFlood flood-opacity="0" result="BackgroundImageFix" />
        <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" />
        <feOffset dy="4" />
        <feGaussianBlur stdDeviation="2" />
        <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0" />
        <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow" />
        <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape" />
      </filter>
    </defs>
  </svg>

  
  <svg class="banner-shape-3" width="39" height="40" viewBox="0 0 39 40" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z" stroke="#040306"
      stroke-miterlimit="10" />
    <path class="path" d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z" />
    <path d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z" stroke="#040306"
      stroke-miterlimit="10" />
  </svg>

  
  <svg class="banner-border" height="240" viewBox="0 0 2202 240" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path
      d="M1 123.043C67.2858 167.865 259.022 257.325 549.762 188.784C764.181 125.427 967.75 112.601 1200.42 169.707C1347.76 205.869 1901.91 374.562 2201 1"
      stroke-width="2" />
  </svg>
</div>
<!-- end of banner -->

  <!-- Main Script -->
  <script src="js/script.js"></script></body>

<div style="margin-top: 40px;">
  <div class = "container d-flex flex-wrap justify-content-center">
    <div class = "row" >
      <% @recipe_facade.recipes.each do |recipe| %>
        <div class ="col-lg-4 col-md-6 col-sm-12">
          <div class = "card h-100">
            <div class = "card recipe-card">
              <%= link_to recipe_path(recipe.id) do %>
                <img src="<%= recipe.img_src %>" alt="<%= recipe.name %>" class="card-img-top">
              <% end %>
              <div class="card-body d-flex flex-column justify-content-center align-items-center">
                <h5 class="card-title"><%= link_to recipe.name, recipe_path(recipe.id) %></h5>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

</html>

app/views/recipes/new.html.erb
<%= form_with url: recipes_path, method: :post, multipart: true do |form| %>
  <div>
    <%= form.label :title, 'Title:' %>
    <%= form.text_field :title, required: true %>
  </div>
  <div>
    <%= form.label :servings, 'Servings:' %>
    <%= form.number_field :servings, required: true %>
  </div>
  <div>
    <%= form.label :prep_time, 'Prep Time:' %>
    <%= form.text_field :prep_time, required: true %>
  </div>
  <div>
    <%= form.label :ingredients, 'Ingredients:' %>
    <%= form.text_area :ingredients, rows: 4, required: true %>
  </div>
  <div>
    <%= form.label :instructions, 'Instructions:' %>
    <%= form.text_area :instructions, rows: 4, required: true %>
  </div>
  <div>
    <%= form.label :image, 'Image:' %>
    <%= form.file_field :image, direct_upload: true, required: true, accept: 'image/*' %>
  </div>
  <%= form.submit 'Create Recipe' %>
<% end %>

app/views/recipes/show.html.erb
  <!-- navigation -->
<header class="navigation fixed-top">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-white">
      <a class="navbar-brand order-1" href="/recipes">
        <h2>KindKitchen</h2>
      </a>
      <div class="collapse navbar-collapse text-center order-lg-2 order-3" id="navigation">
        <ul class="navbar-nav mx-auto">

        <ul class="navbar-nav ms-auto">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "My Dashboard", dashboard_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%#= link_to "Register", register_path, class: 'nav-link' %>
              <%= link_to "Create Account", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%#= link_to "Log In", login_path, class: 'nav-link' %>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        </ul>
      </div>

      <div class="order-2 order-lg-3 d-flex align-items-center">
        
        <!-- search -->
        <%= form_with url: recipes_path, method: :get, local: true, data: {turbo: false}, class: "header-search-form" do |f| %>
          <%= f.text_field :search, placeholder: "Search by Ingredients..." %>
          <%= f.submit "Search" %>
        <% end %>
      </div>

    </nav>
  </div>
</header>
<!-- /navigation -->
<div class="banner text-center">
<br><h1><%= @recipe_facade.recipe.name %></h1>
<div class="d-flex justify-content-center">
  <% if current_user %>
    <br><%= button_to "Save Recipe", user_recipes_path, method: :post, data: {turbo: false}, params: {user_id: current_user.id, recipe_id: @recipe_facade.search} %>
  <% end %>
</div>
<br><img src="<%= @recipe_facade.recipe.img_src %>" alt="<%= @recipe_facade.recipe.name %>">
<br><b>Servings</b>: <%= @recipe_facade.recipe.servings %>
<br><b>Prep Time</b>: <%= @recipe_facade.recipe.cooking_time %> Minutes
<br>
<br><b><u>Ingredients</u></b>
<% @recipe_facade.recipe.ingredients.each do |ingredient| %>
                    <br><%= ingredient %>
                    <% end %>
                    <br>
<br><b><u>Instructions</u></b>
<div class="text-left">
<% @recipe_facade.recipe.instructions.each do |instruction| %>
                    <% instruction.each do |number, step| %>
                      <br><b><%= number %>)</b> <%= step %>
                    <% end %>
                  <% end %>
  </div>
</div>